
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code on this fresh ubuntu OS
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pylint  # Install pylint
      
    - name: Set Python path
      run: |
        export PYTHONPATH=$(pwd)
    - name: Run Tests
      run: |
        pytest ADMIN/test_app.py --maxfail=1 --disable-warnings



    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up a unique tag for our docker image
      id: tag
      run: echo "tag=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USERNAME}}/simple-docker-hub:${{ env.tag }}

    - name: Push the Docker image to our DockerHub repo Simple Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/simple-docker-hub:${{ env.tag }}